import crypto from 'node:crypto';
import { serverConfig } from '../config';

// Rotating office QR token — ported verbatim from AttendDesk. The HMAC secret
// (QR_TOKEN_SECRET) must match AttendDesk's so tokens generated by one client
// validate on the other. ±1 window of skew tolerance.

const BASE32_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

function base32(bytes, length) {
  let bits = 0;
  let value = 0;
  let out = '';
  for (const b of bytes) {
    value = (value << 8) | b;
    bits += 8;
    while (bits >= 5) {
      out += BASE32_ALPHABET[(value >>> (bits - 5)) & 0x1f];
      bits -= 5;
    }
  }
  if (bits > 0) out += BASE32_ALPHABET[(value << (5 - bits)) & 0x1f];
  return out.slice(0, length);
}

export function qrTokenForWindow(windowIndex, organizationId) {
  const buf = Buffer.alloc(12);
  buf.writeBigUInt64BE(BigInt(windowIndex), 0);
  const orgHash = crypto.createHash('sha256').update(organizationId).digest();
  buf.writeUInt32BE(orgHash.readUInt32BE(0), 8);
  const mac = crypto.createHmac('sha256', serverConfig.qr.secret).update(buf).digest();
  return base32(mac, 10);
}

export function currentQrToken(organizationId, now = new Date()) {
  const windowSec = serverConfig.qr.windowSeconds;
  const nowSec = Math.floor(now.getTime() / 1000);
  const windowIndex = Math.floor(nowSec / windowSec);
  const validFromSec = windowIndex * windowSec;
  return {
    token: qrTokenForWindow(windowIndex, organizationId),
    windowIndex,
    validFrom: new Date(validFromSec * 1000),
    validUntil: new Date((validFromSec + windowSec) * 1000),
  };
}

export function validateQrToken(presented, organizationId, now = new Date()) {
  const windowSec = serverConfig.qr.windowSeconds;
  const nowSec = Math.floor(now.getTime() / 1000);
  const current = Math.floor(nowSec / windowSec);
  for (const w of [current, current - 1]) {
    const expected = qrTokenForWindow(w, organizationId);
    if (
      expected.length === presented.length &&
      crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(presented))
    ) {
      const validFromSec = w * windowSec;
      return {
        valid: true,
        windowIndex: w,
        validFrom: new Date(validFromSec * 1000),
        validUntil: new Date((validFromSec + windowSec) * 1000),
      };
    }
  }
  return { valid: false };
}
